Terrain_Types = [
	{
		checksum = TERRAIN_DEFAULT
		desc = 'Default'
	}
	{
		checksum = TERRAIN_CONCSMOOTH
		desc = 'ConcSmooth'
	}
	{
		checksum = TERRAIN_CONCROUGH
		desc = 'ConcRough'
	}
	{
		checksum = TERRAIN_METALSMOOTH
		desc = 'MetalSmooth'
	}
	{
		checksum = TERRAIN_METALROUGH
		desc = 'MetalRough'
	}
	{
		checksum = TERRAIN_METALCORRUGATED
		desc = 'MetalCorrugated'
	}
	{
		checksum = TERRAIN_METALGRATING
		desc = 'MetalGrating'
	}
	{
		checksum = TERRAIN_METALTIN
		desc = 'MetalTin'
	}
	{
		checksum = TERRAIN_WOOD
		desc = 'Wood'
	}
	{
		checksum = TERRAIN_WOODMASONITE
		desc = 'WoodMasonite'
	}
	{
		checksum = TERRAIN_WOODPLYWOOD
		desc = 'WoodPlywood'
	}
	{
		checksum = TERRAIN_WOODFLIMSY
		desc = 'WoodFlimsy'
	}
	{
		checksum = TERRAIN_WOODSHINGLE
		desc = 'WoodShingle'
	}
	{
		checksum = TERRAIN_WOODPIER
		desc = 'WoodPier'
	}
	{
		checksum = TERRAIN_BRICK
		desc = 'Brick'
	}
	{
		checksum = TERRAIN_TILE
		desc = 'Tile'
	}
	{
		checksum = TERRAIN_ASPHALT
		desc = 'Asphalt'
	}
	{
		checksum = TERRAIN_ROCK
		desc = 'Rock'
	}
	{
		checksum = TERRAIN_GRAVEL
		desc = 'Gravel'
	}
	{
		checksum = TERRAIN_SIDEWALK
		desc = 'Sidewalk'
	}
	{
		checksum = TERRAIN_GRASS
		desc = 'Grass'
	}
	{
		checksum = TERRAIN_GRASSDRIED
		desc = 'GrassDried'
	}
	{
		checksum = TERRAIN_DIRT
		desc = 'Dirt'
	}
	{
		checksum = TERRAIN_DIRTPACKED
		desc = 'DirtPacked'
	}
	{
		checksum = TERRAIN_WATER
		desc = 'Water'
	}
	{
		checksum = TERRAIN_ICE
		desc = 'Ice'
	}
	{
		checksum = TERRAIN_SNOW
		desc = 'Snow'
	}
	{
		checksum = TERRAIN_SAND
		desc = 'Sand'
	}
	{
		checksum = TERRAIN_PLEXIGLASS
		desc = 'Plexiglass'
	}
	{
		checksum = TERRAIN_FIBERGLASS
		desc = 'Fiberglass'
	}
	{
		checksum = TERRAIN_CARPET
		desc = 'Carpet'
	}
	{
		checksum = TERRAIN_CONVEYOR
		desc = 'Conveyor'
	}
	{
		checksum = TERRAIN_CHAINLINK
		desc = 'Chainlink'
	}
	{
		checksum = TERRAIN_METALFUTURE
		desc = 'MetalFuture'
	}
	{
		checksum = TERRAIN_GENERIC1
		desc = 'Generic1'
	}
	{
		checksum = TERRAIN_GENERIC2
		desc = 'Generic2'
	}
	{
		checksum = TERRAIN_WHEELS
		desc = 'Wheels'
	}
	{
		checksum = TERRAIN_WETCONC
		desc = 'WetConc'
	}
	{
		checksum = TERRAIN_METALFENCE
		desc = 'MetalFence'
	}
	{
		checksum = TERRAIN_GRINDTRAIN
		desc = 'GrindTrain'
	}
	{
		checksum = TERRAIN_GRINDROPE
		desc = 'GrindRope'
	}
	{
		checksum = TERRAIN_GRINDWIRE
		desc = 'Grindwire'
	}
	{
		checksum = TERRAIN_GRINDCONC
		desc = 'GrindConc'
	}
	{
		checksum = TERRAIN_GRINDROUNDMETALPOLE
		desc = 'GrindRoundMetalPole'
	}
	{
		checksum = TERRAIN_GRINDCHAINLINK
		desc = 'GrindChainLink'
	}
	{
		checksum = TERRAIN_GRINDMETAL
		desc = 'GrindMetal'
	}
	{
		checksum = TERRAIN_GRINDWOODRAILING
		desc = 'GrindWoodRailing'
	}
	{
		checksum = TERRAIN_GRINDWOODLOG
		desc = 'GrindWoodLog'
	}
	{
		checksum = TERRAIN_GRINDWOOD
		desc = 'GrindWood'
	}
	{
		checksum = TERRAIN_GRINDPLASTIC
		desc = 'GrindPlastic'
	}
	{
		checksum = TERRAIN_GRINDELECTRICWIRE
		desc = 'GrindElectricWire'
	}
	{
		checksum = TERRAIN_GRINDCABLE
		desc = 'GrindCable'
	}
	{
		checksum = TERRAIN_GRINDCHAIN
		desc = 'GrindChain'
	}
	{
		checksum = TERRAIN_GRINDPLASTICBARRIER
		desc = 'GrindPlasticBarrier'
	}
	{
		checksum = TERRAIN_GRINDNEONLIGHT
		desc = 'GrindNeonLight'
	}
	{
		checksum = TERRAIN_GRINDGLASSMONSTER
		desc = 'GrindGlassMonster'
	}
	{
		checksum = TERRAIN_GRINDBANYONTREE
		desc = 'GrindBAnyOnTree'
	}
	{
		checksum = TERRAIN_GRINDBRASSRAIL
		desc = 'GrindBrassRail'
	}
	{
		checksum = TERRAIN_GRINDCATWALK
		desc = 'GrindCatwalk'
	}
	{
		checksum = TERRAIN_GRINDTANKTURRET
		desc = 'GrindTankTurret'
	}
]
Terrain_Actions = [
]

script SetTerrainDefault 
	LoadTerrainSounds \{terrain = TERRAIN_DEFAULT}
endscript

script SetTerrainMetalSmooth 
	LoadTerrainSounds \{terrain = TERRAIN_METALSMOOTH}
endscript
STANDARD_TERRAIN_DEFAULT = {
	SoundActions = {
		SoundAssets = TERRAIN_DEFAULT_SoundAssets
		SKATE_AIR = TERRAIN_SKATE_DEFAULT_AIR
		SKATE_ROLL = TERRAIN_SKATE_DEFAULT_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_DEFAULT_OLLIE
		SKATE_LAND = TERRAIN_SKATE_DEFAULT_LAND
		SKATE_BONK = TERRAIN_SKATE_DEFAULT_BONK
		SKATE_GRIND = TERRAIN_SKATE_DEFAULT_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_DEFAULT_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_DEFAULT_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_DEFAULT_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_DEFAULT_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_DEFAULT_SLIDELAND
		SKATE_REVERT = TERRAIN_SKATE_DEFAULT_REVERT
		BIKE_AIR = TERRAIN_BIKE_DEFAULT_AIR
		BIKE_ROLL = TERRAIN_BIKE_DEFAULT_ROLL
		BIKE_OLLIE = TERRAIN_BIKE_DEFAULT_OLLIE
		BIKE_LAND = TERRAIN_BIKE_DEFAULT_LAND
		BIKE_BONK = TERRAIN_BIKE_DEFAULT_BONK
		BIKE_GRIND = TERRAIN_BIKE_DEFAULT_GRIND
		BIKE_GRINDJUMP = TERRAIN_BIKE_DEFAULT_GRINDJUMP
		BIKE_GRINDLAND = TERRAIN_BIKE_DEFAULT_GRINDLAND
	}
	treadActions = {
		SkaterGrindParticleParms = [
			{
				skater_sparks_params
			}
		]
	}
}
STANDARD_TERRAIN_CONCSMOOTH = {
	SoundActions = {
		SoundAssets = TERRAIN_CONCSMOOTH_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_CONCSMOOTH_ROLL
		SKATE_GRIND = TERRAIN_SKATE_CONCSMOOTH_GRIND
		SKATE_LAND = TERRAIN_SKATE_CONCSMOOTH_LAND
		SKATE_BONK = TERRAIN_SKATE_CONCSMOOTH_BONK
		SKATE_GRINDJUMP = TERRAIN_SKATE_CONCSMOOTH_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_CONCSMOOTH_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_CONCSMOOTH_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_CONCSMOOTH_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_CONCSMOOTH_SLIDELAND
		SKATE_REVERT = TERRAIN_SKATE_CONCSMOOTH_REVERT
	}
}
STANDARD_TERRAIN_CONCROUGH = {
	SoundActions = {
		SoundAssets = TERRAIN_CONCROUGH_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_CONCROUGH_ROLL
		SKATE_GRIND = TERRAIN_SKATE_CONCROUGH_GRIND
		SKATE_LAND = TERRAIN_SKATE_CONCROUGH_LAND
		SKATE_BONK = TERRAIN_SKATE_CONCROUGH_BONK
		SKATE_GRINDJUMP = TERRAIN_SKATE_CONCROUGH_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_CONCROUGH_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_CONCROUGH_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_CONCROUGH_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_CONCROUGH_SLIDELAND
		SKATE_REVERT = TERRAIN_SKATE_CONCROUGH_REVERT
	}
}
STANDARD_TERRAIN_BRICK = {
	SoundActions = {
		SoundAssets = TERRAIN_DEFAULT_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_BRICK_ROLL
		SKATE_GRIND = TERRAIN_SKATE_BRICK_GRIND
		SKATE_LAND = TERRAIN_SKATE_BRICK_LAND
		SKATE_BONK = TERRAIN_SKATE_BRICK_BONK
		SKATE_GRINDJUMP = TERRAIN_SKATE_BRICK_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_BRICK_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_BRICK_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_BRICK_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_BRICK_SLIDELAND
		SKATE_REVERT = TERRAIN_SKATE_BRICK_REVERT
	}
}
STANDARD_TERRAIN_ASPHALT = {
	SoundActions = {
		SoundAssets = TERRAIN_ASPHALT_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_ASPHALT_ROLL
		SKATE_GRIND = TERRAIN_SKATE_ASPHALT_GRIND
		SKATE_LAND = TERRAIN_SKATE_ASPHALT_LAND
		SKATE_BONK = TERRAIN_SKATE_ASPHALT_BONK
		SKATE_GRINDJUMP = TERRAIN_SKATE_ASPHALT_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_ASPHALT_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_ASPHALT_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_ASPHALT_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_ASPHALT_SLIDELAND
		SKATE_REVERT = TERRAIN_SKATE_ASPHALT_REVERT
	}
}
STANDARD_TERRAIN_SIDEWALK = {
	SoundActions = {
		SoundAssets = TERRAIN_SIDEWALK_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_SIDEWALK_ROLL
		SKATE_GRIND = TERRAIN_SKATE_SIDEWALK_GRIND
		SKATE_LAND = TERRAIN_SKATE_SIDEWALK_LAND
		SKATE_BONK = TERRAIN_SKATE_SIDEWALK_BONK
		SKATE_GRINDJUMP = TERRAIN_SKATE_SIDEWALK_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_SIDEWALK_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_SIDEWALK_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_SIDEWALK_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_SIDEWALK_SLIDELAND
		SKATE_REVERT = TERRAIN_SKATE_SIDEWALK_REVERT
	}
}
STANDARD_TERRAIN_WETCONC = {
	SoundActions = {
		SoundAssets = TERRAIN_WETCONC_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_WETCONC_ROLL
		SKATE_GRIND = TERRAIN_SKATE_WETCONC_GRIND
		SKATE_LAND = TERRAIN_SKATE_WETCONC_LAND
		SKATE_BONK = TERRAIN_SKATE_WETCONC_BONK
		SKATE_GRINDJUMP = TERRAIN_SKATE_WETCONC_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_WETCONC_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_WETCONC_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_WETCONC_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_WETCONC_SLIDELAND
		SKATE_REVERT = TERRAIN_SKATE_WETCONC_REVERT
	}
}
STANDARD_TERRAIN_METALSMOOTH = {
	SoundActions = {
		SoundAssets = TERRAIN_METALSMOOTH_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_METALSMOOTH_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_METALSMOOTH_OLLIE
		SKATE_LAND = TERRAIN_SKATE_METALSMOOTH_LAND
		SKATE_BONK = TERRAIN_SKATE_METALSMOOTH_BONK
		SKATE_REVERT = TERRAIN_SKATE_METALSMOOTH_REVERT
	}
}
STANDARD_TERRAIN_METALROUGH = {
	SoundActions = {
		SoundAssets = TERRAIN_METALROUGH_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_METALROUGH_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_METALROUGH_OLLIE
		SKATE_LAND = TERRAIN_SKATE_METALROUGH_LAND
		SKATE_BONK = TERRAIN_SKATE_METALROUGH_BONK
		SKATE_REVERT = TERRAIN_SKATE_METALROUGH_REVERT
	}
}
STANDARD_TERRAIN_METALCORRUGATED = {
	SoundActions = {
		SoundAssets = TERRAIN_METALCORRUGATED_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_METALCORRUGATED_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_METALCORRUGATED_OLLIE
		SKATE_LAND = TERRAIN_SKATE_METALCORRUGATED_LAND
		SKATE_BONK = TERRAIN_SKATE_METALCORRUGATED_BONK
		SKATE_REVERT = TERRAIN_SKATE_METALCORRUGATED_REVERT
	}
}
STANDARD_TERRAIN_METALGRATING = {
	SoundActions = {
		SoundAssets = TERRAIN_METALGRATING_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_METALGRATING_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_METALGRATING_OLLIE
		SKATE_LAND = TERRAIN_SKATE_METALGRATING_LAND
		SKATE_BONK = TERRAIN_SKATE_METALGRATING_BONK
		SKATE_REVERT = TERRAIN_SKATE_METALGRATING_REVERT
	}
}
STANDARD_TERRAIN_METALTIN = {
	SoundActions = {
		SoundAssets = TERRAIN_METALTIN_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_METALTIN_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_METALTIN_OLLIE
		SKATE_LAND = TERRAIN_SKATE_METALTIN_LAND
		SKATE_BONK = TERRAIN_SKATE_METALTIN_BONK
		SKATE_REVERT = TERRAIN_SKATE_METALTIN_REVERT
	}
}
STANDARD_TERRAIN_WOOD = {
	SoundActions = {
		SoundAssets = TERRAIN_WOOD_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_WOOD_ROLL
		SKATE_GRIND = TERRAIN_SKATE_WOOD_GRIND
		SKATE_OLLIE = TERRAIN_SKATE_WOOD_OLLIE
		SKATE_LAND = TERRAIN_SKATE_WOOD_LAND
		SKATE_BONK = TERRAIN_SKATE_WOOD_BONK
		SKATE_GRINDJUMP = TERRAIN_SKATE_WOOD_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_WOOD_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_WOOD_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_WOOD_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_WOOD_SLIDELAND
		SKATE_REVERT = TERRAIN_SKATE_WOOD_REVERT
	}
}
STANDARD_TERRAIN_WOODMASONITE = {
	SoundActions = {
		SoundAssets = TERRAIN_WOODMASONITE_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_WOODMASONITE_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_WOODMASONITE_OLLIE
		SKATE_LAND = TERRAIN_SKATE_WOODMASONITE_LAND
		SKATE_BONK = TERRAIN_SKATE_WOODMASONITE_BONK
		SKATE_REVERT = TERRAIN_SKATE_WOODMASONITE_REVERT
	}
}
STANDARD_TERRAIN_WOODPLYWOOD = {
	SoundActions = {
		SoundAssets = TERRAIN_WOODPLYWOOD_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_WOODPLYWOOD_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_WOODPLYWOOD_OLLIE
		SKATE_LAND = TERRAIN_SKATE_WOODPLYWOOD_LAND
		SKATE_BONK = TERRAIN_SKATE_WOODPLYWOOD_BONK
		SKATE_REVERT = TERRAIN_SKATE_WOODPLYWOOD_REVERT
	}
}
STANDARD_TERRAIN_WOODFLIMSY = {
	SoundActions = {
		SoundAssets = TERRAIN_WOODFLIMSY_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_WOODFLIMSY_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_WOODFLIMSY_OLLIE
		SKATE_LAND = TERRAIN_SKATE_WOODFLIMSY_LAND
		SKATE_BONK = TERRAIN_SKATE_WOODFLIMSY_BONK
		SKATE_REVERT = TERRAIN_SKATE_WOODFLIMSY_REVERT
	}
}
STANDARD_TERRAIN_WOODSHINGLE = {
	SoundActions = {
		SoundAssets = TERRAIN_WOODSHINGLE_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_WOODSHINGLE_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_WOODSHINGLE_OLLIE
		SKATE_LAND = TERRAIN_SKATE_WOODSHINGLE_LAND
		SKATE_BONK = TERRAIN_SKATE_WOODSHINGLE_BONK
		SKATE_REVERT = TERRAIN_SKATE_WOODSHINGLE_REVERT
	}
}
STANDARD_TERRAIN_WOODPIER = {
	SoundActions = {
		SoundAssets = TERRAIN_WOODPIER_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_WOODPIER_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_WOODPIER_OLLIE
		SKATE_LAND = TERRAIN_SKATE_WOODPIER_LAND
		SKATE_BONK = TERRAIN_SKATE_WOODPIER_BONK
		SKATE_REVERT = TERRAIN_SKATE_WOODPIER_REVERT
	}
}
STANDARD_TERRAIN_ROCK = {
	SoundActions = {
		SoundAssets = TERRAIN_ROCK_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_ROCK_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_ROCK_OLLIE
		SKATE_LAND = TERRAIN_SKATE_ROCK_LAND
		SKATE_REVERT = TERRAIN_SKATE_ROCK_REVERT
	}
}
STANDARD_TERRAIN_GRAVEL = {
	SoundActions = {
		SoundAssets = TERRAIN_GRAVEL_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_GRAVEL_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_GRAVEL_OLLIE
		SKATE_LAND = TERRAIN_SKATE_GRAVEL_LAND
		SKATE_REVERT = TERRAIN_SKATE_GRAVEL_REVERT
	}
	treadActions = {
		SkaterSkatingParticleParms = [
			{
				apm_gravel01_particle_params
			}
		]
		SkaterStepParticleParms = [
			{
				apm_Skater_gravel01_fast_particle_params
			}
		]
	}
}
STANDARD_TERRAIN_GRASS = {
	SoundActions = {
		SoundAssets = TERRAIN_GRASS_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_GRASS_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_GRASS_OLLIE
		SKATE_LAND = TERRAIN_SKATE_GRASS_LAND
		SKATE_REVERT = TERRAIN_SKATE_GRASS_REVERT
	}
	treadActions = {
		SkaterSkatingParticleParms = [
			{
				apm_grass01_particle_params
			}
		]
	}
}
STANDARD_TERRAIN_GRASSDRIED = {
	SoundActions = {
		SoundAssets = TERRAIN_GRASSDRIED_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_GRASSDRIED_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_GRASSDRIED_OLLIE
		SKATE_LAND = TERRAIN_SKATE_GRASSDRIED_LAND
		SKATE_REVERT = TERRAIN_SKATE_GRASSDRIED_REVERT
	}
}
STANDARD_TERRAIN_DIRT = {
	SoundActions = {
		SoundAssets = TERRAIN_DIRT_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_DIRT_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_DIRT_OLLIE
		SKATE_LAND = TERRAIN_SKATE_DIRT_LAND
		SKATE_REVERT = TERRAIN_SKATE_DIRT_REVERT
	}
	treadActions = {
		SkaterSkatingParticleParms = [
			{
				apm_dirt_puff01_particle_params
			}
		]
		SkaterStepParticleParms = [
			{
				apm_dirt_puff02_particle_params
			}
		]
	}
}
STANDARD_TERRAIN_DIRTPACKED = {
	SoundActions = {
		SoundAssets = TERRAIN_DIRTPACKED_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_DIRTPACKED_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_DIRTPACKED_OLLIE
		SKATE_LAND = TERRAIN_SKATE_DIRTPACKED_LAND
		SKATE_REVERT = TERRAIN_SKATE_DIRTPACKED_REVERT
	}
}
STANDARD_TERRAIN_WATER = {
	SoundActions = {
		SoundAssets = TERRAIN_WATER_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_WATER_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_WATER_OLLIE
		SKATE_LAND = TERRAIN_SKATE_WATER_LAND
	}
	treadActions = {
		SkaterSkatingParticleParms = [
			{
				apm_water_wake02_particle_params
			}
			{
				apm_water_wake03_particle_params
			}
		]
		SkaterStepParticleParms = [
			{
				apm_Skater_splash03_fast_particle_params
			}
			{
				apm_water_wake01_particle_params
			}
		]
		HeroContinuousParticleParams = apm_waterring01_particle_params
	}
}
STANDARD_TERRAIN_ICE = {
	SoundActions = {
		SoundAssets = TERRAIN_ICE_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_ICE_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_ICE_OLLIE
		SKATE_LAND = TERRAIN_SKATE_ICE_LAND
		SKATE_REVERT = TERRAIN_SKATE_ICE_REVERT
	}
}
STANDARD_TERRAIN_SNOW = {
	SoundActions = {
		SoundAssets = TERRAIN_SNOW_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_SNOW_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_SNOW_OLLIE
		SKATE_LAND = TERRAIN_SKATE_SNOW_LAND
		SKATE_REVERT = TERRAIN_SKATE_SNOW_REVERT
	}
}
STANDARD_TERRAIN_SAND = {
	SoundActions = {
		SoundAssets = TERRAIN_SAND_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_SAND_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_SAND_OLLIE
		SKATE_LAND = TERRAIN_SKATE_SAND_LAND
		SKATE_REVERT = TERRAIN_SKATE_SAND_REVERT
	}
	treadActions = {
		SkaterSkatingParticleParms = [
			{
				apm_sand_puff01_particle_params
			}
		]
		SkaterStepParticleParms = [
			{
				apm_sand_puff02_particle_params
			}
		]
	}
}
STANDARD_TERRAIN_TILE = {
	SoundActions = {
		SoundAssets = TERRAIN_TILE_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_TILE_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_TILE_OLLIE
		SKATE_LAND = TERRAIN_SKATE_TILE_LAND
		SKATE_REVERT = TERRAIN_SKATE_TILE_REVERT
	}
}
STANDARD_TERRAIN_PLEXIGLASS = {
	SoundActions = {
		SoundAssets = TERRAIN_PLEXIGLASS_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_PLEXIGLASS_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_PLEXIGLASS_OLLIE
		SKATE_LAND = TERRAIN_SKATE_PLEXIGLASS_LAND
		SKATE_REVERT = TERRAIN_SKATE_PLEXIGLASS_REVERT
	}
}
STANDARD_TERRAIN_FIBERGLASS = {
	SoundActions = {
		SoundAssets = TERRAIN_FIBERGLASS_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_FIBERGLASS_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_FIBERGLASS_OLLIE
		SKATE_LAND = TERRAIN_SKATE_FIBERGLASS_LAND
		SKATE_REVERT = TERRAIN_SKATE_FIBERGLASS_REVERT
	}
}
STANDARD_TERRAIN_CARPET = {
	SoundActions = {
		SoundAssets = TERRAIN_CARPET_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_CARPET_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_CARPET_OLLIE
		SKATE_LAND = TERRAIN_SKATE_CARPET_LAND
		SKATE_REVERT = TERRAIN_SKATE_CARPET_REVERT
	}
}
STANDARD_TERRAIN_CONVEYOR = {
	SoundActions = {
		SoundAssets = TERRAIN_CONVEYOR_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_CONVEYOR_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_CONVEYOR_OLLIE
		SKATE_LAND = TERRAIN_SKATE_CONVEYOR_LAND
		SKATE_REVERT = TERRAIN_SKATE_CONVEYOR_REVERT
	}
}
STANDARD_TERRAIN_CHAINLINK = {
	SoundActions = {
		SoundAssets = TERRAIN_CHAINLINK_SoundAssets
		SKATE_BONK = TERRAIN_SKATE_CHAINLINK_BONK
		SKATE_GRIND = TERRAIN_SKATE_CHAINLINK_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_CHAINLINK_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_CHAINLINK_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_CHAINLINK_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_CHAINLINK_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_CHAINLINK_SLIDELAND
	}
}
STANDARD_TERRAIN_METALFUTURE = {
	SoundActions = {
		SoundAssets = TERRAIN_METALFUTURE_SoundAssets
		SKATE_ROLL = TERRAIN_SKATE_METALFUTURE_ROLL
		SKATE_OLLIE = TERRAIN_SKATE_METALFUTURE_OLLIE
		SKATE_LAND = TERRAIN_SKATE_METALFUTURE_LAND
		SKATE_REVERT = TERRAIN_SKATE_METALFUTURE_REVERT
	}
}
STANDARD_TERRAIN_GENERIC1 = {
	SoundActions = {
		SoundAssets = TERRAIN_GENERIC1_SoundAssets
		SKATE_BONK = TERRAIN_SKATE_GENERIC1_BONK
	}
}
STANDARD_TERRAIN_GENERIC2 = {
	SoundActions = {
		SoundAssets = TERRAIN_GENERIC2_SoundAssets
	}
}
STANDARD_TERRAIN_METALFENCE = {
	SoundActions = {
		SoundAssets = TERRAIN_METALFENCE_SoundAssets
		SKATE_BONK = TERRAIN_SKATE_METALFENCE_BONK
	}
}
STANDARD_TERRAIN_GRINDCONC = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDCONC_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDCONC_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDCONC_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDCONC_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDCONC_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDCONC_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDCONC_SLIDELAND
	}
	treadActions = {
		SkaterGrindParticleParms = [
			{
				skater_sparks_params
			}
			{
				APM_Debris01_particle_params
			}
		]
		SkaterSlideParticleParms = [
		]
	}
}
STANDARD_TERRAIN_GRINDROUNDMETALPOLE = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDROUNDMETALPOLE_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDROUNDMETALPOLE_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDROUNDMETALPOLE_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDROUNDMETALPOLE_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDROUNDMETALPOLE_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDROUNDMETALPOLE_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDROUNDMETALPOLE_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDCHAINLINK = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDCHAINLINK_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDCHAINLINK_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDCHAINLINK_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDCHAINLINK_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDCHAINLINK_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDCHAINLINK_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDCHAINLINK_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDMETAL = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDMETAL_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDMETAL_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDMETAL_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDMETAL_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDMETAL_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDMETAL_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDMETAL_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDWOODRAILING = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDWOODRAILING_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDWOODRAILING_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDWOODRAILING_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDWOODRAILING_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDWOODRAILING_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDWOODRAILING_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDWOODRAILING_SLIDELAND
	}
	treadActions = {
		SkaterGrindParticleParms = [
			{
				apm_splinter01_particle_params
			}
		]
		SkaterSlideParticleParms = [
			{
				apm_splinter01_particle_params
			}
		]
	}
}
STANDARD_TERRAIN_GRINDWOODLOG = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDWOODLOG_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDWOODLOG_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDWOODLOG_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDWOODLOG_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDWOODLOG_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDWOODLOG_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDWOODLOG_SLIDELAND
	}
	treadActions = {
		SkaterGrindParticleParms = [
			{
				apm_splinter01_particle_params
			}
		]
		SkaterSlideParticleParms = [
			{
				apm_splinter01_particle_params
			}
		]
	}
}
STANDARD_TERRAIN_GRINDWOOD = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDWOOD_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDWOOD_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDWOOD_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDWOOD_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDWOOD_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDWOOD_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDWOOD_SLIDELAND
	}
	treadActions = {
		SkaterGrindParticleParms = [
			{
				apm_splinter01_particle_params
			}
		]
		SkaterSlideParticleParms = [
			{
				apm_splinter01_particle_params
			}
		]
	}
}
STANDARD_TERRAIN_GRINDPLASTIC = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDPLASTIC_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDPLASTIC_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDPLASTIC_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDPLASTIC_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDPLASTIC_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDPLASTIC_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDPLASTIC_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDCHAIN = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDCHAIN_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDCHAIN_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDCHAIN_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDCHAIN_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDCHAIN_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDCHAIN_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDCHAIN_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDELECTRICWIRE = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDELECTRICWIRE_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDELECTRICWIRE_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDELECTRICWIRE_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDELECTRICWIRE_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDELECTRICWIRE_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDELECTRICWIRE_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDELECTRICWIRE_SLIDELAND
	}
	treadActions = {
		SkaterGrindParticleParms = [
			{
				skater_elec_sparks_params
			}
		]
		SkaterSlideParticleParms = [
		]
	}
}
STANDARD_TERRAIN_GRINDCABLE = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDCABLE_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDCABLE_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDCABLE_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDCABLE_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDCABLE_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDCABLE_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDCABLE_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDPLASTICBARRIER = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDPLASTICBARRIER_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDPLASTICBARRIER_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDPLASTICBARRIER_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDPLASTICBARRIER_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDPLASTICBARRIER_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDPLASTICBARRIER_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDPLASTICBARRIER_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDNEONLIGHT = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDNEONLIGHT_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDNEONLIGHT_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDNEONLIGHT_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDNEONLIGHT_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDNEONLIGHT_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDNEONLIGHT_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDNEONLIGHT_SLIDELAND
	}
	treadActions = {
		SkaterGrindParticleParms = [
			{
				skater_elec_sparks_params
			}
		]
		SkaterSlideParticleParms = [
		]
	}
}
STANDARD_TERRAIN_GRINDGLASSMONSTER = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDGLASSMONSTER_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDGLASSMONSTER_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDGLASSMONSTER_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDGLASSMONSTER_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDGLASSMONSTER_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDGLASSMONSTER_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDGLASSMONSTER_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDBANYONTREE = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDBANYONTREE_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDBANYONTREE_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDBANYONTREE_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDBANYONTREE_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDBANYONTREE_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDBANYONTREE_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDBANYONTREE_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDBRASSRAIL = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDBRASSRAIL_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDBRASSRAIL_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDBRASSRAIL_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDBRASSRAIL_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDBRASSRAIL_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDBRASSRAIL_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDBRASSRAIL_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDCATWALK = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDCATWALK_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDCATWALK_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDCATWALK_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDCATWALK_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDCATWALK_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDCATWALK_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDCATWALK_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDTANKTURRET = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDTANKTURRET_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDTANKTURRET_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDTANKTURRET_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDTANKTURRET_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDTANKTURRET_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDTANKTURRET_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDTANKTURRET_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDTRAIN = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDTRAIN_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDTRAIN_GRIND
	}
}
STANDARD_TERRAIN_GRINDROPE = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDROPE_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDROPE_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDROPE_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDROPE_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDROPE_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDROPE_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDROPE_SLIDELAND
	}
}
STANDARD_TERRAIN_GRINDWIRE = {
	SoundActions = {
		SoundAssets = TERRAIN_GRINDWIRE_SoundAssets
		SKATE_GRIND = TERRAIN_SKATE_GRINDWIRE_GRIND
		SKATE_GRINDJUMP = TERRAIN_SKATE_GRINDWIRE_GRINDJUMP
		SKATE_GRINDLAND = TERRAIN_SKATE_GRINDWIRE_GRINDLAND
		SKATE_SLIDE = TERRAIN_SKATE_GRINDWIRE_SLIDE
		SKATE_SLIDEJUMP = TERRAIN_SKATE_GRINDWIRE_SLIDEJUMP
		SKATE_SLIDELAND = TERRAIN_SKATE_GRINDWIRE_SLIDELAND
	}
	treadActions = {
		SkaterGrindParticleParms = [
			{
				skater_elec_sparks_params
			}
		]
		SkaterSlideParticleParms = [
		]
	}
}
TERRAIN_DEFAULT = STANDARD_TERRAIN_DEFAULT
TERRAIN_CONCSMOOTH = STANDARD_TERRAIN_CONCSMOOTH
TERRAIN_CONCROUGH = STANDARD_TERRAIN_CONCROUGH
TERRAIN_METALSMOOTH = STANDARD_TERRAIN_METALSMOOTH
TERRAIN_METALROUGH = STANDARD_TERRAIN_METALROUGH
TERRAIN_METALCORRUGATED = STANDARD_TERRAIN_METALCORRUGATED
TERRAIN_METALGRATING = STANDARD_TERRAIN_METALGRATING
TERRAIN_METALTIN = STANDARD_TERRAIN_METALTIN
TERRAIN_WOOD = STANDARD_TERRAIN_WOOD
TERRAIN_WOODMASONITE = STANDARD_TERRAIN_WOODMASONITE
TERRAIN_WOODPLYWOOD = STANDARD_TERRAIN_WOODPLYWOOD
TERRAIN_WOODFLIMSY = STANDARD_TERRAIN_WOODFLIMSY
TERRAIN_WOODSHINGLE = STANDARD_TERRAIN_WOODSHINGLE
TERRAIN_WOODPIER = STANDARD_TERRAIN_WOODPIER
TERRAIN_BRICK = STANDARD_TERRAIN_BRICK
TERRAIN_TILE = STANDARD_TERRAIN_TILE
TERRAIN_ASPHALT = STANDARD_TERRAIN_ASPHALT
TERRAIN_ROCK = STANDARD_TERRAIN_ROCK
TERRAIN_GRAVEL = STANDARD_TERRAIN_GRAVEL
TERRAIN_SIDEWALK = STANDARD_TERRAIN_SIDEWALK
TERRAIN_GRASS = STANDARD_TERRAIN_GRASS
TERRAIN_GRASSDRIED = STANDARD_TERRAIN_GRASSDRIED
TERRAIN_DIRT = STANDARD_TERRAIN_DIRT
TERRAIN_DIRTPACKED = STANDARD_TERRAIN_DIRTPACKED
TERRAIN_WATER = STANDARD_TERRAIN_WATER
TERRAIN_ICE = STANDARD_TERRAIN_ICE
TERRAIN_SNOW = STANDARD_TERRAIN_SNOW
TERRAIN_SAND = STANDARD_TERRAIN_SAND
TERRAIN_PLEXIGLASS = STANDARD_TERRAIN_PLEXIGLASS
TERRAIN_FIBERGLASS = STANDARD_TERRAIN_FIBERGLASS
TERRAIN_CARPET = STANDARD_TERRAIN_CARPET
TERRAIN_CONVEYOR = STANDARD_TERRAIN_CONVEYOR
TERRAIN_CHAINLINK = STANDARD_TERRAIN_CHAINLINK
TERRAIN_METALFUTURE = STANDARD_TERRAIN_METALFUTURE
TERRAIN_GENERIC1 = STANDARD_TERRAIN_GENERIC1
TERRAIN_GENERIC2 = STANDARD_TERRAIN_GENERIC2
TERRAIN_WHEELS = STANDARD_TERRAIN_WHEELS
TERRAIN_WETCONC = STANDARD_TERRAIN_WETCONC
TERRAIN_METALFENCE = STANDARD_TERRAIN_METALFENCE
TERRAIN_GRINDTRAIN = STANDARD_TERRAIN_GRINDTRAIN
TERRAIN_GRINDROPE = STANDARD_TERRAIN_GRINDROPE
TERRAIN_GRINDWIRE = STANDARD_TERRAIN_GRINDWIRE
TERRAIN_GRINDCONC = STANDARD_TERRAIN_GRINDCONC
TERRAIN_GRINDROUNDMETALPOLE = STANDARD_TERRAIN_GRINDROUNDMETALPOLE
TERRAIN_GRINDCHAINLINK = STANDARD_TERRAIN_GRINDCHAINLINK
TERRAIN_GRINDMETAL = STANDARD_TERRAIN_GRINDMETAL
TERRAIN_GRINDWOODRAILING = STANDARD_TERRAIN_GRINDWOODRAILING
TERRAIN_GRINDWOODLOG = STANDARD_TERRAIN_GRINDWOODLOG
TERRAIN_GRINDWOOD = STANDARD_TERRAIN_GRINDWOOD
TERRAIN_GRINDPLASTIC = STANDARD_TERRAIN_GRINDPLASTIC
TERRAIN_GRINDELECTRICWIRE = STANDARD_TERRAIN_GRINDELECTRICWIRE
TERRAIN_GRINDCABLE = STANDARD_TERRAIN_GRINDCABLE
TERRAIN_GRINDCHAIN = STANDARD_TERRAIN_GRINDCHAIN
TERRAIN_GRINDPLASTICBARRIER = STANDARD_TERRAIN_GRINDPLASTICBARRIER
TERRAIN_GRINDNEONLIGHT = STANDARD_TERRAIN_GRINDNEONLIGHT
TERRAIN_GRINDGLASSMONSTER = STANDARD_TERRAIN_GRINDGLASSMONSTER
TERRAIN_GRINDBANYONTREE = STANDARD_TERRAIN_GRINDBANYONTREE
TERRAIN_GRINDBRASSRAIL = STANDARD_TERRAIN_GRINDBRASSRAIL
TERRAIN_GRINDCATWALK = STANDARD_TERRAIN_GRINDCATWALK
TERRAIN_GRINDTANKTURRET = STANDARD_TERRAIN_GRINDTANKTURRET
